### ISSUE TITLE
This app tracks and reports your activity

### ISSUE THREAD

**Issue by glepretre** [twinone/AppLocker#16]
Hello,

I would like to try your app but this warning on F-droid scares me a little.

![screenshot_2015-06-03-10-28-59](https://cloud.githubusercontent.com/assets/5930831/7956357/9fce914e-09df-11e5-8d70-377d3abfa7d5.png)

Could you explain me why F-droid warns about it?

**Comment by twinone** [comment]
Hi, it was because I sent some anonymous statistics about usage (number of
correct unlocks, etc) to my server so I could improve it better, but I
actually didn't use them and in the last release I removed it so it doesn't
even use internet at all in the F-Droid store, just in Google store to show
ads.

Best
Luuk (Twinone)

**Comment by glepretre** [comment]
Thanks for your answers! :wink:

I understand now, as you can see the F-droid version is dated March 16, so it doesn't include your two latest commits.

**Comment by twinone** [comment]
Oh, I forgot to add the release. I'll do it right away!
