### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by glepretre** [twinone/AppLocker#17]
Hello,

Could you explain why your app needs these permissions please?
    
    <uses-permission android:name="android.permission.PROCESS_OUTGOING_CALLS" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />

I have some idea but I have not found any clear explanation anywhere (Play store features list, F-droid description, README...).

Thank you :wink:

**Comment by venkat20390** [comment]
I am not a developer of the app. But i could tell you the reason for this permission, since i am an android developer.

1. Outgoing call - The app provides an option to hide the app icon from app drawer to prevent others from knowing which app lock is being used. Once the icon is hidden, then user need to dial a particular number to launch the app again. Hence this outgoing call permission.
2. Internet - It is for providing ads and implementing analytics.
3. Access Network state & WiFi - Probably to provide WiFi based unlocking feature for the app.

**Comment by twinone** [comment]
Exactly, but note that:
- The unlock with wifi was experimental, it's never gone into production.
- Ads are only displayed in the Google Play version.
- I've removed analytics in 715ed87b518bd81e935e6285e367269a0e56cd06
